### ISSUE TITLE
[Опечатка] Rust глава 3

### ISSUE THREAD

**Issue by viteo** [senjun-team/senjun-courses#159]
"**_Типа_** пакета имеет длину 1 байт" -> "**_Тип_** пакета имеет длину 1 байт"
https://github.com/senjun-team/senjun-courses/blob/a9d2065820339a06191852e9a71b6dd49e83a3f5/rust/rust_chapter_0030/text.md?plain=1#L329

**Comment by Microvenator** [comment]
Спасибо! Фикс поедет на прод в https://github.com/senjun-team/senjun-courses/pull/161

**Comment by Microvenator** [comment]
На проде!
