### ISSUE TITLE
Добавить ФИО получателя в раздел с донатами

### ISSUE THREAD

**Issue by cumamon-san** [senjun-team/senjun-courses#30]
Для большей уверенности стоит добавить ФИО получателя при донате по номеру телефона. Вот здесь:

![Screenshot_2024-04-13-01-58-17-00_a4ede73591b7865c03a3ec33e4c1e611](https://github.com/senjun-team/senjun-courses/assets/54323689/00f49b9e-55cd-4a25-8463-34dacfb3ae06)

**Comment by 1hvh** [comment]
Я бы еще скан паспорта и ИНН добавил

**Comment by deksden** [comment]
Правильное предложение! Для большей безопасности можно добавить имя /отчество и первую букву фамилии.

**Comment by Microvenator** [comment]
Готово.
