### ISSUE TITLE
Сложности с вводом ответов в бот на iOS за счет автозамены символов

### ISSUE THREAD

**Issue by deksden** [senjun-team/senjun-courses#31]
Столкнулся с неочевидными сложностями с вводом ответов в бот на iOS. 

1) Кавычки на стандартной клавиатуре в свежей iOS 17.4 отправляются как слегка наклонные двойные кавычки " вместо прямых " которые ожидает бот. Вводить неудобно. 

2) Также iOS заменяет три точки подряд ... на символ троеточие … 

Выглядит многоточие при этом за счет кернинга оч похоже на три точки подряд, что смутило при неправильном ответе на тривиальную задачку в операторе match курса python. 

Это то, что заметил сейчас. Возможно, будут еще фишки - напишу дополнительно! 

Предложение: обрабатывать поступающие с iOS ответы перед проверкой, заменяя обратно эти "красивые" знаки на обычные символы.

**Comment by deksden** [comment]
Еще проблема с одиночной кавычкой:' вместо ожидаемой '

**Comment by Microvenator** [comment]
Спасибо! Да, действительно. Есть такая проблема. Постараемся это поправить. Как только сделаем, попросим вас потестить)

**Comment by deksden** [comment]
> Постараемся это поправить. 

Думаю, банальная замена символов по таблице замены сможет всё решить! Нужно просто добавить эту предобработку до прочих манипуляций с ответом пользователя. Ситуаций, когда прям необходимо сохранить исходное оформление я в контексте работы бота даже придумать не могу, поэтому всё кажется просто реализовать

**Comment by Microvenator** [comment]
@deksden  выкатили замену:

” -> "
“ -> "
‘ -> '
’ -> '
… -> ...

Можешь пожалуйста проверить, все ли хорошо? И нужно ли что-то еще заменять?

**Comment by Microvenator** [comment]
Готово.
