### ISSUE TITLE
Опечатка в курсе по python, пример кода в главе 4 patter matching

### ISSUE THREAD

**Issue by deksden** [senjun-team/senjun-courses#32]
Скрин: 

![image](https://github.com/senjun-team/senjun-courses/assets/2203023/3c226283-13cf-4fa8-b571-7d4b00ba45d7)

В последней строке кода вместо input должно быть user_input

**Comment by Microvenator** [comment]
Большое спасибо! Поправили: https://github.com/senjun-team/senjun-courses/pull/39
