### ISSUE TITLE
Тренажер ошибочно принимает неполный код как верный.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#34]
## Описание проблемы
Тренажер отмечает неполный код как верный.

## Шаги для воспроизведения проблемы
1. Перейдите в главу 4 - "Тернарный if" - Замените if/else на тернарный оператор.
2. Введите следующий код:
    ```python
    # % 2 == 0 else
    print("""8 even
    3 odd
    16 even""")
    ```
3. Запустите код.

## Ожидаемый результат
Тренажер должен указать, что код неполный или некорректный.
There is no valid ternary operator for setting 'res'

## Фактический результат
Тренажер отмечает код как верный.

## Приложения
![Screenshot 2024-04-13 220546](https://github.com/senjun-team/senjun-courses/assets/81284552/6804558a-5529-4a11-a189-f00bd965b56a)

**Comment by Microvenator** [comment]
Это нормально) Позиция авторов площадки следующая: разработчик проходит курсы добровольно. А не как в универе "пройти любой ценой, иначе не поставят зачет" или как на работе "если я не сдам этот тест, мне не повысят грейд". Иными словами, в интересах пользователя решать задачи честно. Если пользователь читерит, то он вредит сам себе.

Соответственно юнит-тесты направлены на проверку честных решений. Ни одной проверки на абьюз тестов у нас нет и не будет.

Например, для этой задачи мы делаем две проверки:
- Сравниваем консольный вывод с ожидаемым.
- Проверяем, что в коде решения содержится кусок тернарного оператора: удаляем из кода все пробелы и ищем `%2==0else`.

**Comment by khva** [comment]
Хотелось бы добавить, что решение задач не является обязательным и не открывает скрытого 'контента'. Авторами предполагается, что обучающиеся читают главы и решают задачи, потому что им это полезно и интересно.

**Comment by ZhikharevAl** [comment]
## При проведении данных тестов, корректные решения могут не проходить.


```python
for val in [8, 3, 16]:
    res = ["odd", "even"][val % 2 == 0]
    print(val, res)
```

```python
for val in [8, 3, 16]:
    print(f"{val} {'odd' if val % 2 else 'even'}")
```
