### ISSUE TITLE
Лишний пробел перед знаком препинания в тексте.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#35]
## Описание проблемы
В тексте обнаружен лишний пробел перед знаком препинания.

## Шаги для воспроизведения проблемы
1. Перейдите в главу 7 - Лямбда-функции

## Детали
В тексте "параметры :" обнаружен лишний пробел перед двоеточием.

## Ожидаемый результат
Текст должен быть без пробела перед знаком препинания, например: "параметры:".

## Фактический результат
Текст отображается с пробелом перед знаком препинания, например: "параметры :".

## Приложения
![Screenshot 2024-04-14 1656441](https://github.com/senjun-team/senjun-courses/assets/81284552/0e960f15-57a1-41ff-ab96-949aea729f84)
![Screenshot 2024-04-14 1658042](https://github.com/senjun-team/senjun-courses/assets/81284552/0dfd5c78-b51d-4121-abd4-5107f8f3c264)
### Из документации
![Screenshot 2024-04-14 165457](https://github.com/senjun-team/senjun-courses/assets/81284552/91c2c414-15b8-4ea2-a81e-b54f9652ff32)

**Comment by Microvenator** [comment]
Большое спасибо! Поправили: https://github.com/senjun-team/senjun-courses/pull/39
