### ISSUE TITLE
Неправильное использование запятой после союза ‘тем не менее’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#36]
## Описание проблемы
Неправильное использование запятой после союза "тем не менее".

## Шаги для воспроизведения проблемы
1. Перейдите в главу 2  - Исключения из правил.

## Детали
В тексте используется запятая после союза "тем не менее", что является ошибкой.
Если предложение начинается словами «тем не менее», они выступают в качестве союза, и запятая после них не ставится: «Тем не менее».

## Ожидаемый результат
Союз "тем не менее" должен использоваться без запятой после него.

## Фактический результат
В тексте используется запятая после союза "тем не менее".

## Приложения
![Screenshot 2024-04-14 172522](https://github.com/senjun-team/senjun-courses/assets/81284552/a532ce59-4328-4ded-ab6d-6bd13d02993b)

**Comment by Microvenator** [comment]
Большое спасибо! Нам очень не хватало такого грамотного взгляда на курсы! Исправлено: https://github.com/senjun-team/senjun-courses/pull/39
