### ISSUE TITLE
Предложение не начинается с заглавной буквы.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#37]
## Описание проблемы
Предложение не начинается с заглавной буквы.

## Шаги для воспроизведения проблемы
1. Перейдите в главу 4 - pattern matching: когда if/else становится мало

## Детали
В тексте "pattern matching: когда if/else становится мало" первое слово начинается со строчной буквы.

## Ожидаемый результат
Предложение должно начинаться с заглавной буквы.

## Фактический результат
Предложение начинается со строчной буквы.

## Приложения
![Screenshot 2024-04-14 175741](https://github.com/senjun-team/senjun-courses/assets/81284552/79e9caa1-5565-4bfa-9f26-c31368f6b29f)

**Comment by Microvenator** [comment]
Большое спасибо! Исправлено: https://github.com/senjun-team/senjun-courses/pull/39

**Comment by ZhikharevAl** [comment]
Хорошо, как будет время посмотрю.
