### ISSUE TITLE
Неправильное написание слова ‘перемудрённый’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#38]
## Описание проблемы
Неправильное написание слова "перемудреный".

## Шаги для воспроизведения проблемы
1. Перейдите в главу 6 - Параметры и аргументы функции

## Детали
В тексте используется слово "перемудреный", которое написано неправильно.

## Ожидаемый результат
Слово должно быть написано как "перемудрённый".

## Фактический результат
Слово написано как "перемудреный".

## Приложения
![Screenshot 2024-04-14 182501](https://github.com/senjun-team/senjun-courses/assets/81284552/79662a92-15d0-4dd1-8395-7ffab67b0016)

**Comment by Microvenator** [comment]
Большое спасибо! Исправлено: https://github.com/senjun-team/senjun-courses/pull/39
