### ISSUE TITLE
Неправильное использование запятой после слова ‘Однако’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#40]
## Описание проблемы
Неправильное использование запятой после слова "Однако".

## Шаги для воспроизведения проблемы
1.  RUST - Перейдите в главу 1 - Типизация

## Детали
В тексте используется запятая после слова "Однако", что является ошибкой. Слово "однако" в начале предложения не бывает вводным словом, обычно это союз, и запятая в этом случае не нужна.

## Ожидаемый результат
Слово "Однако" в начале предложения должно быть без запятой после него, так как оно выступает в роли союза.

## Фактический результат
В тексте используется запятая после слова "Однако".

## Приложения
![Screenshot 2024-04-14 200314](https://github.com/senjun-team/senjun-courses/assets/81284552/cff86ab1-8ac5-44a0-9f9d-e0653dbc59ae)

**Comment by Microvenator** [comment]
Большое спасибо за ваш труд! Вы нам очень помогли этим и соседними issue.

Фикс уехал вместе с остальными: https://github.com/senjun-team/senjun-courses/pull/51
