### ISSUE TITLE
Пропущена запятая после слова ‘Наверное’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#41]
## Описание проблемы
Пропущена запятая после слова "Наверное".

##
## Шаги для воспроизведения проблемы
1. Rust - Глава1 — Типизация

## Детали
В тексте используется фраза "Наверное это", где пропущена запятая после слова "Наверное".

## Ожидаемый результат
Фраза должна быть написана как "Наверное, это".

## Фактический результат
Фраза написана как "Наверное это".

## Приложения
![Screenshot 2024-04-14 201946](https://github.com/senjun-team/senjun-courses/assets/81284552/8a3bd177-bd56-423e-8740-61cf04c2fbc6)

**Comment by Microvenator** [comment]
Спасибо! Исправили это и похожие случаи: https://github.com/senjun-team/senjun-courses/pull/51
