### ISSUE TITLE
Пропущена запятая в сложном предложении.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#42]
## Описание проблемы
Отсутствует запятая в предложении "Все проверки корректности выполнения правил владения и заимствования происходят во время компиляции.".

## Шаги для воспроизведения проблемы
1.  Rust - Глава 1 - Безопасная работа с памятью

## Детали
В тексте отсутствует запятая после слова "владения", что является ошибкой. Правильно будет: "выполнения правил владения, и заимствования происходят".

## Ожидаемый результат
Предложение должно быть с запятой после слова "владения".

## Фактический результат
В тексте отсутствует запятая после слова "владения".

## Приложения
![Screenshot 2024-04-14 202945](https://github.com/senjun-team/senjun-courses/assets/81284552/913346be-c08f-47e5-be04-7a98ec54fbad)

**Comment by Microvenator** [comment]
Кажется, тут запятая не нужна. Оба слова (владения и заимствования) относятся к "правил". То есть не "заимствования происходят", а "проверки корректности выполнения правил происходят".

**Comment by ZhikharevAl** [comment]
У меня тоже тут сомнения были. Некоторые автопроверки ставят запятую, а некоторые нет. Вот совет от одного из инструментов:
> проверки корректности выполнения правил владения — возможно, излишнее усложнение
Совет: попробуйте сократить, если возможно

Соглашусь что не нужна запятая.
