### ISSUE TITLE
Отсутствует запятая.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#43]
## Описание проблемы
Отсутствует запятая в предложении "Rust создавался в том числе как язык системного программирования.".

## Шаги для воспроизведения проблемы
1.  Rust - Глава 1 - Производительность

## Детали
В тексте отсутствует запятая после слова "создавался", что является ошибкой. Правильно будет: "создавался, в том числе".

## Ожидаемый результат
Предложение должно быть с запятой после слова "создавался".

## Фактический результат
В тексте отсутствует запятая после слова "создавался".

## Приложения
![Screenshot 2024-04-14 211546](https://github.com/senjun-team/senjun-courses/assets/81284552/20b70ad1-9313-4166-a7ac-a73dfd397c7f)

**Comment by Microvenator** [comment]
Спасибо! Исправили: https://github.com/senjun-team/senjun-courses/pull/51
