### ISSUE TITLE
Орфографическая ошибка в слове ‘синтаксическое’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#44]
## Описание проблемы
Орфографическая ошибка в слове "синтактическое". Правильно будет "синтаксическое".

## Шаги для воспроизведения проблемы
1. Rust - Глава 1 - Метапрограммирование

## Детали
В тексте используется неправильное написание слова "синтаксическое". Вместо "синтаксическое" написано "синтактическое".

## Ожидаемый результат
Слово "синтаксическое" должно быть написано правильно.

## Фактический результат
В тексте используется неправильное написание слова "синтаксическое".

## Приложения
![Screenshot 2024-04-14 212449](https://github.com/senjun-team/senjun-courses/assets/81284552/598dbc62-8040-435a-9afd-75c9b9302426)

**Comment by Microvenator** [comment]
Спасибо! Исправили: https://github.com/senjun-team/senjun-courses/pull/51
