### ISSUE TITLE
Сложный союз в начале предложения. Запятые не нужны: «Для того чтобы».

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#45]
## Описание проблемы
Неправильное использование запятых с союзом "Для того чтобы".

## Шаги для воспроизведения проблемы
1. Rust - Глава 2 - Объявление и использование переменных

## Детали
Для того чтобы — составной союз в начале предложения. Запятая между словами, входящими в состав союза, не ставится. Правильно будет: "Для того чтобы" без запятых.

## Ожидаемый результат
Союз "Для того чтобы" должен быть без запятых.

## Фактический результат
В тексте используются запятые в союзе "Для того, чтобы".

## Приложения
![Screenshot 2024-04-14 234607](https://github.com/senjun-team/senjun-courses/assets/81284552/bb3d568f-abe3-4a0c-ac25-e3652320ef2b)

**Comment by Microvenator** [comment]
Спасибо! Исправили: https://github.com/senjun-team/senjun-courses/pull/51
