### ISSUE TITLE
Орфографическая ошибка в слове ‘рассказано’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#47]
## Описание проблемы
Орфографическая ошибка в слове "рассказно". Правильно будет "рассказано".

## Шаги для воспроизведения проблемы
1. Rust - Глава 2 - Область видимости и затенение переменных

## Детали
В тексте используется неправильное написание слова "рассказано". Вместо "рассказано" написано "рассказно".

## Ожидаемый результат
Слово "рассказано" должно быть написано правильно.

## Фактический результат
В тексте используется неправильное написание слова "рассказано".

## Приложения
![Screenshot 2024-04-15 001221](https://github.com/senjun-team/senjun-courses/assets/81284552/b09989da-523c-41c4-8cdc-fe862b660860)

**Comment by Microvenator** [comment]
Спасибо! Исправили: https://github.com/senjun-team/senjun-courses/pull/51
