### ISSUE TITLE
Опечатка в слове "воспользовались"

### ISSUE THREAD

**Issue by msednev** [senjun-team/senjun-courses#53]
Вместо "воспользовалсь", дожно быть "воспользовались".
https://github.com/senjun-team/senjun-courses/blob/6d8fd5ebf1af1d599275267142d37fbaacd12ff2/python/python_chapter_0240/text.md?plain=1#L260

**Comment by Microvenator** [comment]
Большое спасибо! Поправили https://github.com/senjun-team/senjun-courses/pull/57
