### ISSUE TITLE
Орфографическая ошибка в словосочетании ‘несмотря на’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#54]
## Описание проблемы
Орфографическая ошибка в словосочетании "не смотря на". Правильно будет "несмотря на".

## Шаги для воспроизведения проблемы
1. Python - Глава 9 - Числа - Цепочки сравнений

## Детали
В тексте используется неправильное написание словосочетания "несмотря на". Вместо "несмотря на" написано "не смотря на".
В этом предложении «несмотря на» — это отглагольный предлог, который пишется слитно. Его значение — «вопреки чему-то».

## Ожидаемый результат
Словосочетание "несмотря на" должно быть написано слитно.

## Фактический результат
В тексте используется разделенное написание словосочетания "несмотря на".

## Приложения
![Screenshot 2024-04-15 201604](https://github.com/senjun-team/senjun-courses/assets/81284552/6ef14efc-d242-4ec8-94f4-91111efb5828)

**Comment by Microvenator** [comment]
Спасибо! Поправили здесь и в других местах: https://github.com/senjun-team/senjun-courses/pull/57 https://github.com/senjun-team/senjun-courses/pull/58
