### ISSUE TITLE
Пропущена запятая после слова ‘такие’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#60]
## Описание проблемы
Пропущена запятая после слова "такие" в предложении: "Неизменяемые коллекции (такие как кортежи) могут быть хешируемыми..."

## Шаги для воспроизведения проблемы
1. Python - Глава 14 - Объекты, которые можно хранить в set, frozenset и dict.

## Детали
В тексте пропущена запятая после слова "такие", что является ошибкой. Правильно будет: "Неизменяемые коллекции (такие, как кортежи) могут быть хешируемыми..."
Такой (,) как, местоимение + союз. По общему правилу, обороты с союзом «как» выделяются запятыми, если в основной части предложения имеется указательное слово «такой». 

## Ожидаемый результат
После слова "такие" должна стоять запятая.

## Фактический результат
В тексте пропущена запятая после слова "такие".

## Приложения
![Screenshot 2024-04-16 211555](https://github.com/senjun-team/senjun-courses/assets/81284552/bd17490a-d039-40de-83ff-6faf00bcc678)

**Comment by ZhikharevAl** [comment]
Так этот пример к другому правилу.
> Однако в некоторых случаях запятая ставится не перед словом «как», а перед словом «такой»:

Я руководствовался самым началом правила:
>Такой (,) как
ТАКОЙ (,) КАК, местоимение + союз
По общему правилу, обороты с союзом «как» выделяются запятыми, если в основной части предложения имеется указательное слово «такой». 

Например: 
> Быть может, только такие люди, как Шиллер, могли быть достойны ее любви.
Неизменяемые коллекции (такие коллекции, как кортежи) могут быть хешируемыми...

**Comment by ShipilovDmitry** [comment]
В пункте [2](url) говорится, что после обобщающего слова запятая ставится. В нашем случае обобщающее слово «коллекции» находится за пределами скобок. 

Не известно как слова до скобок  оказывают влияние на пунктуацию внутри скобок. Такого правила русского языка я не нашел. Если бы скобок не было, нужно ставить запятую после «такие».

Предлагаю оставить как есть либо убрать скобки и запятую поставить.

**Comment by ZhikharevAl** [comment]
Согласен, запятая не нужна. Выражение ‘такие как кортежи’ является вставной конструкцией в предложении, которая служит для приведения примера или уточнения.
