### ISSUE TITLE
Орфографическая ошибка в слове ‘автоинкремента’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#63]
## Описание проблемы
Орфографическая ошибка в слове "автоинкремента". В тексте написано "авто-инкремента".

## Шаги для воспроизведения проблемы
1. Python - Глава 16 - Атрибуты объекта и атрибуты класса

## Детали
В тексте используется неправильное написание слова "автоинкремента". Вместо "автоинкремента" написано "авто-инкремента".

## Ожидаемый результат
Слово "автоинкремента" должно быть написано слитно.

## Фактический результат
В тексте используется разделенное написание слова "автоинкремента".

## Приложения
![Screenshot 2024-04-16 231210](https://github.com/senjun-team/senjun-courses/assets/81284552/d7d22613-f0f8-4c83-9ea6-346d83f34e24)

**Comment by Microvenator** [comment]
Спасибо! Исправлено: https://github.com/senjun-team/senjun-courses/pull/70
