### ISSUE TITLE
Использование несуществующего слова ‘отнаследовать’ в тексте.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#64]
## Описание проблемы
Использование несуществующего слова "отнаследовать" в тексте.

## Шаги для воспроизведения проблемы
1. Python - Глава 17 - Наследование 

## Детали
В тексте используется слово "отнаследовать", которое не существует в русском языке. Возможно, имелось в виду слово "наследовать" или "унаследовать".

## Ожидаемый результат
В тексте должны использоваться только существующие и корректные слова.
1.  Унаследуем класс InMemoryStorage от него(базовый класс Storage).
2. У класса в питоне можно вызвать метод mro(), который возвращает список классов, от которых наследован данный.
3. Cache наследован от ABC...
    Унаследуем от Cache специализированную...
4. Чтобы можно было создавать объекты классов, наследованных от абстрактного...
    Превратите класс Navigation (построения маршрутов) в абстрактный класс. Унаследуйте от него 2 класса...
## Фактический результат
В тексте используется несуществующее слово "отнаследовать".

## Приложения
![Screenshot 2024-04-16 234027](https://github.com/senjun-team/senjun-courses/assets/81284552/eb16b3b2-366b-4c93-a7bd-35c452d852be)
![Screenshot 2024-04-16 234422](https://github.com/senjun-team/senjun-courses/assets/81284552/011a58d8-418e-4685-b90a-a3c15a7f486a)
![Screenshot 2024-04-16 234504](https://github.com/senjun-team/senjun-courses/assets/81284552/eb490956-9fb9-46ad-8794-269c16e49341)
![Screenshot 2024-04-16 234548](https://github.com/senjun-team/senjun-courses/assets/81284552/5a8e3bbb-14d3-4fa2-b972-2f3695695e61)

**Comment by Microvenator** [comment]
Спасибо! Поправили все вхождения. https://github.com/senjun-team/senjun-courses/pull/70
