### ISSUE TITLE
Форматирование абзацев

### ISSUE THREAD

**Issue by bergentroll** [senjun-team/senjun-courses#67]
По нормам русского языка первая строка абзаца имеет отступ (обычно 1,25 или 1,27 см).

Так же колонка текста не очень широкая и поэтому выравнивание по левому краю выглядит неопрятно. Было бы здорово иметь выравнивание по ширине, хотя бы опционально.

**Comment by Microvenator** [comment]
Добрый день!

Действительно, у нас отсутствуют отступы, а текст выровнен по левому краю. Мы делаем это по той же самой причине, почему так делается в различных мессенджерах, на информационных ресурсах (хабр, онлайн-журнал Мир Фантастики и вообще подавляющее большинство площадок):
- Отсутствие отступа экономит место на мобилках.
- Выравнивание по левому краю гарантирует, что если в строке мало слов, но они длинные, читателю будет комфортно. Иначе между словами возникнут большие расстояния, а такой текст читается хуже.

Субъективно мне и самой больше нравится выравнивание по ширине. Но выбирая между красотой и удобством, мы выбрали удобство) Когда у нас появится больше ресурсов на разработку, подобные вещи мы действительно сможем кастомизировать и выносить в опции)
