### ISSUE TITLE
Предложение не начинается с заглавной буквы.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#73]
## Описание проблемы

Предложение "assert не является средством для обработки ошибок." начинается с маленькой буквы.

## Шаги для воспроизведения проблемы

1. Python - Глава 19 - Инструкция assert

## Детали

- Контекст: Обсуждение использования assert в Python
В тексте "assert не является средством для обработки ошибок." первое слово начинается со строчной буквы.

## Ожидаемый результат

Предложение должно начинаться с большой буквы: "Assert не является средством для обработки ошибок."

## Фактический результат

Предложение начинается с маленькой буквы: "assert не является средством для обработки ошибок."

## Приложения
![Screenshot 2024-04-17 184312](https://github.com/senjun-team/senjun-courses/assets/81284552/2264a6c1-001c-4930-9e59-755e0d2e5ebb)

**Comment by Microvenator** [comment]
Спасибо! Поправили: https://github.com/senjun-team/senjun-courses/pull/80
