### ISSUE TITLE
Орфографическая ошибка в слове  ‘псевдослучайных’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#74]
## Описание проблемы
Орфографическая ошибка в слове "псевдослучайных". В тексте написано "псевдо-случайных".

## Шаги для воспроизведения проблемы
1. Python - Глава 20 - Основные библиотечные модули

## Детали
В тексте используется неправильное написание слова "псевдослучайных". Вместо "псевдослучайных" написано "псевдо-случайных".

## Ожидаемый результат
Слово "псевдослучайных" должно быть написано слитно.

## Фактический результат
В тексте используется разделенное написание слова "псевдослучайных".

## Приложения
![Screenshot 2024-04-17 185421](https://github.com/senjun-team/senjun-courses/assets/81284552/d7e6c38a-5488-4ad9-a0c0-7ade9b8f58ce)

**Comment by Microvenator** [comment]
Спасибо! Поправили: https://github.com/senjun-team/senjun-courses/pull/80
