### ISSUE TITLE
Неформальная форма глагола в техническом тексте.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#75]
## Описание проблемы

В предложении "И в строках 1-2 сгенерится исключение." используется неформальная форма глагола "сгенерировать".

## Шаги для воспроизведения проблемы

1. Python - Глава 21 - Мотивация

## Детали

В тексте используется форма глагола "сгенерится", которая является неформальной и не всегда приемлемой в технической литературе. Возможно, имелось в виду использование более формальной формы "сгенерируется".

## Ожидаемый результат

Предложение должно использовать более формальную форму глагола: "И в строках 1-2 сгенерируется исключение."

## Фактический результат

В предложении используется неформальная форма глагола: "И в строках 1-2 сгенерится исключение."

## Приложения
![Screenshot 2024-04-17 191329](https://github.com/senjun-team/senjun-courses/assets/81284552/169def9c-bceb-4827-a2d9-4bed83c3168d)

**Comment by Microvenator** [comment]
Спасибо! Поправили: https://github.com/senjun-team/senjun-courses/pull/80
