### ISSUE TITLE
Орфографическая ошибка в слове "контролировать".

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#76]
## Описание проблемы

В слове "контроллировать" обнаружена ошибка.

## Шаги для воспроизведения проблемы

1. Python - Глава 21 - Контекстные менеджеры и оператор with

## Детали

В тексте используется слово "контроллировать", в котором допущена ошибка. Возможно, имелось в виду слово "[контролировать](https://ru.wiktionary.org/wiki/контролировать)".

## Ожидаемый результат

Слово должно быть написано как "контролировать".

## Фактический результат

В тексте используется неправильное слово "контроллировать".

## Приложения
![Screenshot 2024-04-17 191727](https://github.com/senjun-team/senjun-courses/assets/81284552/ce9d03c8-528f-4208-a0cf-3a263865b0cf)

**Comment by Microvenator** [comment]
Спасибо! Поправили: https://github.com/senjun-team/senjun-courses/pull/80
