### ISSUE TITLE
Орфографическая ошибка в слове ‘менеджер’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#78]
## Описание проблемы

Обнаружена орфографическая ошибка в слове "менедежр".

## Шаги для воспроизведения проблемы

1. Python - Глава 21 - Протокол контекстного менеджера

## Детали

В тексте используется слово "менедежр", которое является неправильным написанием слова "менеджер".

## Ожидаемый результат

Слово должно быть написано как "менеджер".

## Фактический результат

В тексте используется неправильное написание слова "менеджер": "менедежр".

## Приложения
![Screenshot 2024-04-17 194328](https://github.com/senjun-team/senjun-courses/assets/81284552/0e11e11d-7280-44b7-9880-e3d6bde231c0)

**Comment by Microvenator** [comment]
Спасибо! Поправили: https://github.com/senjun-team/senjun-courses/pull/80
