### ISSUE TITLE
Орфографическая ошибка в слове ‘контринтуитивной’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#79]
## Описание проблемы

Обнаружена ошибка в написании слова "контр-интуитивной".

## Шаги для воспроизведения проблемы

1. Python - Глава 22 - Области видимости

## Детали

В тексте используется слово "контр-интуитивной", которое является неправильным написанием слова "[контринтуитивной](https://ru.m.wiktionary.org/wiki/контринтуитивный)".

## Ожидаемый результат

Слово должно быть написано как "контринтуитивной".

## Фактический результат

В тексте используется неправильное написание слова "контринтуитивной": "контр-интуитивной".

## Приложения
![Screenshot 2024-04-17 194947](https://github.com/senjun-team/senjun-courses/assets/81284552/e45fbc11-b986-416b-862a-33f4639d3ad7)

**Comment by Microvenator** [comment]
Спасибо! Поправили: https://github.com/senjun-team/senjun-courses/pull/80
