### ISSUE TITLE
Отсутствие необходимых запятых.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#81]
## Описание проблемы

В предложении "Оператор моржа := может использоваться внутри comprehensions для того чтобы избежать повторных вычислений одних и тех же данных." отсутствуют необходимые запятые.

## Шаги для воспроизведения проблемы

1. Python - Глава 24 - Оператор моржа внутри comprehensions

## Детали

В тексте отсутствуют запятые, которые должны обособлять оборот "для того, чтобы", являющийся вводным словосочетанием.
Оно вводит придаточное предложение цели и обычно обособляется запятыми.

## Ожидаемый результат

Предложение должно быть написано как "Оператор моржа := может использоваться внутри comprehensions, для того, чтобы избежать повторных вычислений одних и тех же данных."

## Фактический результат

В тексте отсутствуют необходимые запятые: "Оператор моржа := может использоваться внутри comprehensions для того чтобы избежать повторных вычислений одних и тех же данных."

## Приложения
![Screenshot 2024-04-17 201518](https://github.com/senjun-team/senjun-courses/assets/81284552/d6ab7630-f128-4890-abb3-8d0e20a96cec)

**Comment by Microvenator** [comment]
Спасибо! @ShipilovDmitry поправил: https://github.com/senjun-team/senjun-courses/pull/89
