### ISSUE TITLE
Орфографическая ошибка в слове ‘эквивалентно’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#82]
## Описание проблемы

В предложении "Это будет эквиваленто передаче именованных аргументов: f(**d)." обнаружена ошибка в написании слова "эквиваленто".

## Шаги для воспроизведения проблемы

1. Python - Глава 25 - Распаковка аргументов функций

## Детали

В тексте используется слово "эквиваленто", которое является неправильным написанием слова "эквивалентно".

## Ожидаемый результат

Слово должно быть написано как "эквивалентно".

## Фактический результат

В тексте используется неправильное написание слова "эквивалентно": "эквиваленто".

## Приложения
![Screenshot 2024-04-17 203154](https://github.com/senjun-team/senjun-courses/assets/81284552/f7e506e9-5d72-45f1-8842-b3228f234c3d)

**Comment by Microvenator** [comment]
Спасибо! @ShipilovDmitry поправил: https://github.com/senjun-team/senjun-courses/pull/89
