### ISSUE TITLE
Отсутствие необходимых запятых в предложении.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#83]
## Описание проблемы

В предложении "Но, к счастью решение есть и имя ему functools.wraps." отсутствуют необходимые запятые.

## Шаги для воспроизведения проблемы

1. Python - Глава 27 - Метаданные функций

## Детали

В тексте отсутствуют запятые, которые должны обособлять оборот "к счастью", являющийся вводным словосочетанием.
Запятые здесь обособляют вводное словосочетание, которое можно опустить без ущерба для основного смысла предложения.

## Ожидаемый результат

Предложение должно быть написано как "Но, к счастью, решение есть и имя ему functools.wraps." 

## Фактический результат

В тексте отсутствуют необходимые запятые: "Но, к счастью решение есть и имя ему functools.wraps."

## Приложения
![Screenshot 2024-04-17 205359](https://github.com/senjun-team/senjun-courses/assets/81284552/1f18671d-af05-419e-a8d1-f0ebb64ea750)

**Comment by Microvenator** [comment]
Спасибо! @ShipilovDmitry поправил: https://github.com/senjun-team/senjun-courses/pull/89
