### ISSUE TITLE
Путаница из-за использования нескольких местоимений ‘их’. 

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#84]
## Описание проблемы

В предложении "Для выполнения их с помощью интерпретатора с GIL их не имеет смысла распараллеливать на потоки." возникает путаница из-за использования местоимения "их".

## Шаги для воспроизведения проблемы

1. Python - Глава 29 - Следствия наличия GIL

## Детали

В тексте используется несколько местоимений "их", что может вызвать путаницу при чтении.

## Ожидаемый результат

Предложение должно быть написано как "Для выполнения этих задач с помощью интерпретатора, который использует GIL, нет смысла распараллеливать их на потоки." Это улучшает читаемость и устраняет возможное недопонимание.

## Фактический результат

В тексте используется местоимение "их", что может вызвать путаницу: "Два их в предложении. Для выполнения их с помощью интерпретатора с GIL их не имеет смысла распараллеливать на потоки."

## Приложения
![Screenshot 2024-04-18 013847](https://github.com/senjun-team/senjun-courses/assets/81284552/64d835ce-78b6-42f6-93bc-fae23031bfff)

**Comment by Microvenator** [comment]
Спасибо! @ShipilovDmitry поправил: https://github.com/senjun-team/senjun-courses/pull/89
