### ISSUE TITLE
Отсутствие необходимых запятых в предложении.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#85]
## Описание проблемы

В предложении "В промышленной разработке как правило просто следует пользоваться стандартным циклом событий, который стоит за вызовами async/await." отсутствуют необходимые запятые.

## Шаги для воспроизведения проблемы

1. Python - Глава 31 - Цикл событий (event loop)

## Детали

В тексте отсутствуют запятые, которые должны обособлять оборот "как правило", являющийся вводным словосочетанием.
Оно вводит придаточное предложение цели и обычно обособляется запятыми. Если фраза находится внутри предложения, играет роль вводной конструкции и может быть заменена синонимом «обычно», «обыкновенно», «чаще всего», запятые нужны с обеих сторон.

## Ожидаемый результат

Предложение должно быть написано как "В промышленной разработке, как правило, просто следует пользоваться стандартным циклом событий, который стоит за вызовами async/await." 

## Фактический результат

В тексте отсутствуют необходимые запятые: "В промышленной разработке как правило просто следует пользоваться стандартным циклом событий, который стоит за вызовами async/await."

## Приложения

![Screenshot 2024-04-18 015953](https://github.com/senjun-team/senjun-courses/assets/81284552/1c1c319f-e32c-4042-936c-4cee8975124c)

**Comment by Microvenator** [comment]
Спасибо! @ShipilovDmitry поправил: https://github.com/senjun-team/senjun-courses/pull/89
