### ISSUE TITLE
Некорректное использование термина ‘не-данные’ в русском языке.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#86]
## Описание проблемы

Слово "не-данные" в тексте используется некорректно в русском языке. 

## Шаги для воспроизведения проблемы

1. Python - Глава 34 - Виды дескрипторов

## Детали
Сочетания с не пишутся либо слитно, либо раздельно, но почти никогда не пишутся через дефис. Слитное слово "неданные" имеет другой смысл - "неврученный".
В тексте используется слово не-данные, которое в русском языке имеет другой смысл. Вместо этого следует использовать слово в кавычках: "не-данные", чтобы подчеркнуть его специфическое или нестандартное использование.

## Ожидаемый результат

Слово "не-данные" должно быть использовано в кавычках: "не-данные".

## Фактический результат

В тексте используется слово не-данные без кавычек, что может вызвать путаницу из-за различия в смысле слова "неданные" в русском языке.

## Приложения
![Screenshot 2024-04-18 023819](https://github.com/senjun-team/senjun-courses/assets/81284552/3161d804-70d3-4a2d-b20a-6ab64feef9b7)
![Screenshot 2024-04-18 023911](https://github.com/senjun-team/senjun-courses/assets/81284552/7220d95c-3205-4256-9a13-fdbe09e002bc)

**Comment by Microvenator** [comment]
Спасибо! @ShipilovDmitry поправил: https://github.com/senjun-team/senjun-courses/pull/89
