### ISSUE TITLE
Структура предложения: стилистический повтор слова ‘чтобы’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#87]
## Описание проблемы

В предложении "Чтобы по-прежнему можно было писать item.number = "78XZ6", но чтобы в момент присваивания запускалась нужная нам валидация и в случае неудачи генерировалось исключение." есть стилистический повтор слова "чтобы".

## Шаги для воспроизведения проблемы

1. Python - Глава 36 - Мотивация

## Детали

В тексте повторяется слово "чтобы", что может снизить читаемость и ухудшить стилистику текста.

## Ожидаемый результат

Предложение должно быть переформулировано для избежания повторения, например: "Нам необходимо, чтобы при присваивании значения item.number = "78XZ6" запускалась соответствующая валидация. В случае неудачи должно генерироваться исключение, при этом возможность присваивания значения должна сохраняться."

## Фактический результат

В тексте есть стилистический повтор: "Чтобы по-прежнему можно было писать item.number = "78XZ6", но чтобы в момент присваивания запускалась нужная нам валидация и в случае неудачи генерировалось исключение."

## Приложения
![Screenshot 2024-04-18 025508](https://github.com/senjun-team/senjun-courses/assets/81284552/a704a6bb-701d-4129-8dca-f416ece93ec1)

**Comment by Microvenator** [comment]
Спасибо! @ShipilovDmitry поправил: https://github.com/senjun-team/senjun-courses/pull/89
