### ISSUE TITLE
Начало предложения со строчной буквы в разделе ‘Type и динамическое создание классов’.

### ISSUE THREAD

**Issue by ZhikharevAl** [senjun-team/senjun-courses#88]
## Описание проблемы

Предложение "type и динамическое создание классов." не начинается с заглавной буквы.

## Шаги для воспроизведения проблемы

1. Python - Глава 37 - Type и динамическое создание классов

## Детали

В тексте предложение начинается со строчной буквы, что нарушает правила русского языка.

## Ожидаемый результат

Предложение должно начинаться с заглавной буквы: "Type и динамическое создание классов."

## Фактический результат

Предложение начинается со строчной буквы: "type и динамическое создание классов."

## Приложения
![Screenshot 2024-04-18 031435](https://github.com/senjun-team/senjun-courses/assets/81284552/b4d76e17-fdd1-459d-826a-647f22e80627)
![Screenshot 2024-04-18 031509](https://github.com/senjun-team/senjun-courses/assets/81284552/410b3eca-0c38-4b2c-9cda-7fd96709b74b)

**Comment by ShipilovDmitry** [comment]
Писать с заглавной буквы будет некорректно, потому что тут имеется ввиду ключевое слово языка. Можно в заголовке написать **type()** со скобками

**Comment by ZhikharevAl** [comment]
Уже исправлено.
