### ISSUE TITLE
Напишите функцию to_dict(items)

### ISSUE THREAD

**Issue by YAKOROLEVAZAMKA** [senjun-team/senjun-courses#95]
https://senjun.ru/courses/python/chapters/python_chapter_0150/

Пишет что не удалось отправить решение на сервер.

1)
import typing

def to_dict(items):
    return {k: idx for idx, k in enumerate(items) if isinstance(k, typing.Hashable)}

2)
to_dict = lambda items: {k: idx for idx, k in enumerate(items) if isinstance(k, typing.Hashable)}

**Comment by YAKOROLEVAZAMKA** [comment]
ванильное решение так же не работает

**Comment by 4500zenja1** [comment]
имхо это были какие-то внутренние траблы с сайтом, сейчас все решения работают
